### ISSUE TITLE
Modificación de mid de campus para manejar nuevo modelo de producción academica

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/campus_mid#21]
Modificación del mid de campus teniendo en cuenta el nuevo modelo de producción academica.

**Comment by JuanPiedrahita** [comment]
Se agrega docker para desarrollo
https://github.com/udistrital/campus_mid/commit/82f1b989eb3e7ce52e43073158ad3e7de44ae5e3

**Comment by JuanPiedrahita** [comment]
Se agrega servicio para produccion academica
https://github.com/udistrital/campus_mid/commit/1fa4d47e691fe001ac0436b777ee8300222d24a6

**Comment by JuanPiedrahita** [comment]
Se permite registrar produccioens academicas
https://github.com/udistrital/campus_mid/commit/221593c9944bf2ff267ddec02fd8eddd1d0f6d51
https://github.com/udistrital/campus_mid/commit/4e6494d3f6ea0a0b3a15c6f82d69389f38373361

**Comment by JuanPiedrahita** [comment]
Listando producciones 
https://github.com/udistrital/campus_mid/commit/bace9f33002bee26bf8930a412c865269ebe785e

**Comment by JuanPiedrahita** [comment]
Borrando producciones 
https://github.com/udistrital/campus_mid/commit/df560912443dec6fad857b11f8f210a832d9b7d6

**Comment by JuanPiedrahita** [comment]
Update de las producciones academicas
https://github.com/udistrital/campus_mid/commit/6a15a69f8e9c9f32a5516f972a4e757079732fac

**Comment by JuanPiedrahita** [comment]
Agegando estados del autor
https://github.com/udistrital/campus_mid/commit/239915c33b7e12c11d79f282136fe83428e43ce3
https://github.com/udistrital/campus_mid/commit/bb6b13d2b2b54a09acc8f5fd4dbc96652f6dd235

**Comment by mafeave** [comment]
Se verifican los commits del desarrollo realizado.
