### ISSUE TITLE
Modificación de mid de campus para manejar modelo de producción academica aprobado

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/campus_mid#22]
Modificación del mid de campus teniendo en cuenta el  modelo de producción academica aprobado.

**Comment by JuanPiedrahita** [comment]
[Carpeta ](https://drive.google.com/drive/folders/1dpOiB80a2TaiQS-4lBQmPLSllbwxX4Wi?usp=sharing)con configuraciones y script de ejemplo para probar.

**Comment by mafeave** [comment]
Se verifican los commits del desarrollo realizado, se envía a Planestic para verificación de la funcionalidad.
