### ISSUE TITLE
Modificación del mid para traer el proyecto curricular con el id de OIKOS

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/campus_mid#24]
Se debe modificar el MID para obneter los eventos relacionado a inscripcion en determinado periodo, debe traer el nombre de la dependencia con el id que entrega el servicio de eventos, el mid debe cumplir con los siguientes requerimientos:

- [x] El mid debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El mid debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del mid para traer el servicio de eventos y el servicio de oikos, para el formulario del cliente para visualizar la oferta academica es necesario traer la dependecia que esta relaciona con el id guardada en el evento, el desarrollo se efectua en el repositorio de [campus_mid](https://github.com/udistrital/campus_mid/tree/consulta_oferta_academica) en la rama de consulta_oferta_academica.

Queda pendiente revisión por parte de la lider tecnica: @mafeave

**Comment by mafeave** [comment]
Se verifica funcionamiento de la función creada para consultar las carreras habilitadas para hacer el proceso de inscripción en un periodo académico determinado.
